

export const CREATE_DATA_START = 'CREATE_DATA_START'
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS'
export const CREATE_DATA_ERROR = 'CREATE_DATA_ERROR'

export const GET_DATA_START = 'GET_DATA_START'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const DELETE_DATA_START = 'DELETE_DATA_START'
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'

export const EDIT_DATA_START = 'EDIT_DATA_START'
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS'
export const EDIT_DATA_ERROR = 'EDIT_DATA_ERROR'

